name: Variables and secrets

env:
  WF_VAR: "WorkFlow level variable"
on:
  push:

jobs:
  test_expression:
    name: job to test expressions
    runs-on: ubuntu-latest
    env: 
      aBoolean: ${{false}}
      aNull: ${{ null }}
      aNumber: ${{ 42 }}
      aString: this is a string
    steps: 
      - name: test null
        if: (env.aNull == null)
        run: echo this variable is null
      - name: test boolean
        if: ${{ fromJSON(env.aBoolean) }}
        run: echo this job wont run as our variable is false'
      - name: contains function
        if: ${{ contains(env.aString, 'this') }}
        run: |
          echo "our string var contains the word this"
          echos "but here is a typo that will make this step fail"
      - name: test status check and format funtion
        if: ${{ failure() }}
        env: 
          FORMAT_VAR: ${{ format('Github {0} {1} {2}', 'actions', 'is', 'awesome!') }}
        run: |
          echo "this step runsa special script to clean up after the failed step"
          echo ${{ env.FORMAT_VAR}}
      - name: funtion and always status check
        if: ${{ startWith(env.aString, 'this') && always() }}
        run: sleep 60
      - name: test cancel status check
        if: ${{ cancelled() }}
        run: echo "this job runs if a workflow is cancelled, it can also be used for clean up scripts"
        
  test_variables:
    if: (github.event_name == 'pul_request')
    env: 
      JOB_VAR: "Job level variable"
    name: job to test variable
    runs-on: ubuntu-latest
    steps:
      - name: test variables
        id: stepVar
        env:
          STEP_VAR: "Step Level variable" 
        run: |
          echo ${{ github.actor}}
          echo $GITHUB_JOB
          echo $WF_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo $${{ vars.CONF_VAR}}
          echo ${{ secrets.A_SECRET}}
